#!/bin/bash

#set -e
set -euo pipefail

exec 3>&1 # make stdout available as file descriptor 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# Read the payload from stdin
payload=$(cat <&0)
url=$(echo "$payload" | jq -r '.source.url')

if [[ -z "${url}" ]]; then
    echo >&2 "Source parameter 'url' is missing"
    exit 1
fi

destination="downloads"

mkdir -p "$destination"

wget -q -O "$destination/fly-cli.tgz" "$url"

tar -xvf "$destination/fly-cli.tgz" -C "$destination/"

chmod +x "$destination/fly"

newVersion=$($destination/fly --version)
>&2 echo "Latest version ${newVersion}"

jq --null-input \
    --arg "version" "${newVersion}" \
    '[ { version: $version } ]' \
    >&3

