#!/bin/bash

set -euo pipefail

exec 3>&1 # make stdout available as file descriptor 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# Read input from stdin
payload=$(cat <&0)
url=$(echo "$payload" | jq -r '.source.url')
version=$(echo "$payload" | jq -r '.version.version')

# Directory where the resource will be placed
destination=$1

# Ensure the destination directory exists
mkdir -p "$destination"

# Download the resource using wget
wget -q -O "$destination/fly-cli.tgz" "$url"

# Write the version to version file
touch $destination/version.txt
echo "$version" > "$destination/version.txt"

# Output the fetched version information
jq -n --arg version "$version" '{version: {version: $version}}' >&3
